### ISSUE TITLE
pdfsizeopt crashing with a sam2p error

### ISSUE THREAD

**Issue by jul059** [pts/pdfsizeopt#160]
windows build from feb 24 2023 crashes on this pdf with a sam2p.exe error. I have encountered other pdfs crashing with the same error. 

command is `pdfsizeopt --use-image-optimizer=ECT,jbig2`

The same command works with the old build.

[sample_sam2p_crash.pdf](https://github.com/pts/pdfsizeopt/files/10875245/sample_sam2p_crash.pdf)

**Comment by pts** [comment]
Thank you for reporting this! Please copy-paste the full console output of pdfsizeopt.

**Comment by pts** [comment]
Indeed, I can reproduce this bug, no need to post the console output. This bug also happens on Linux, the sam2p program in the neweset libexec also crashes there:

```
$ sam2p -j:quiet -pdf:2 -c zip:1:9 -s Gray1:Indexed1:Gray2:Indexed2:Rgb1:Gray4:Indexed4:Rgb2:Gray8:Indexed8:Rgb4:Rgb8:stop -- issue160sub.png issue160sub4.pdf
Segmentation fault (core dumped)
```

Download this to reproduce: [issue160sub.png](https://user-images.githubusercontent.com/379746/223445795-444e9384-b034-4501-a02c-ad58f83a0369.png)

**Comment by pts** [comment]
Fixed in https://github.com/pts/imgdataopt/commit/ccf2b37a2eb4bb009aed06e86a241f4741b628de .

**Comment by jul059** [comment]
On my system with v8, pdfsizeopt is still crashing, but sam2p is not throwing the same error. 

![image](https://user-images.githubusercontent.com/25236477/224370128-d25e629c-eb32-41af-b664-9ee7431beea3.png)

**Comment by pts** [comment]
Indeed, v8 is still buggy, it also fails for me in *img-3126* with the error message *fatal: bad palette size*. This is a diferent bug though, I have to diagnose and fix it in [imgdataopt](https://github.com/pts/imgdataopt). Thank you for your patience.

**Comment by pts** [comment]
Fixed it in https://github.com/pts/imgdataopt/commit/a245e29c04e007d48a6242cdf770f14c690cbce7, and released it in [v9]( (https://github.com/pts/pdfsizeopt/releases/tag/2023-04-18).

New, fixed binaries are available (including the fixed *imgdataopt*, named as *sam2p*). Please reinstall pdfsizeopt by following the instructions on https://github.com/pts/pdfsizeopt.

I've just checked that now pdfsizeopt completes successfully for your [sample_sam2p_crash.pdf](https://github.com/pts/pdfsizeopt/files/10875245/sample_sam2p_crash.pdf). However, it is not able to reduce the file size by much, only around 2%:

```
info: generated 9266221 bytes (98%)
```
